### ISSUE TITLE
Logo not displaying

### ISSUE THREAD

**Issue by Mark-Parker-work** [DataS-DHSC/dhsc_quarto_template#41]
Thanks for publishing this template. When I render from template_DHSC_HTML the logo doesn't display in either the RStudio Viewer or when the rendered html is opened in Edge. The headings, plot, table, and tabset do all display correctly, it's just the logo missing. I get the same result when opening the DHSC_HTML_example html file.

**Comment by Olivia-Box-Power** [comment]
Hi @Mark-Parker-work. This issue should now be fixed. Could you try installing the templates again please and see if it works?
