### ISSUE TITLE
_extension.yml for OHID and DHSC _extensions needs review

### ISSUE THREAD

**Issue by MKatz-DHSC** [DataS-DHSC/dhsc_quarto_template#48]
The _extension.yml files contains redundant options: standalone and toc_float

The _extension.yml files have an incorrectly named option: toc_depth rather than toc-depth (option should have dash rather than underscore).

**Comment by Olivia-Box-Power** [comment]
Thanks @MKatz-DHSC. Fixed and merged into development for next release.
